spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5432/shorturldb
    password: YOUR_PASSWORD
    # Test database
    test:
      diver-class-name: org.h2.Driver
      password: password
      url: jdbc:h2:mem/unit_test_db
      username: sa
  jpa:
    properties:
      hibernate:
        format_sql: "true"
    hibernate:
      ddl-auto: update
      # Test JPA
    test:
      hibernate:
      ddl-auto: create-drop
server:
  port: "8080"
base_url: http://localhost:8080/

springdoc:
  api-docs:
    path: /api-docs
